### ISSUE TITLE
The x flag (set by Cygwin) is not forwarded to MiNT

### ISSUE THREAD

**Issue by mikrosk** [aranym/aranym#22]
As discussed here: https://sourceforge.net/p/freemint/mailman/message/36661133/

The issue is not present on Linux. Tested on latest snapshot.

**Comment by joysfera** [comment]
has Vincent used the latest released ARAnyM? There have been some related fixes, IIRC.

**Comment by mikrosk** [comment]
Not only Vincent but myself as well - I can reproduce it on my Windows 10, too.

**Comment by th-otto** [comment]
That must be a Windows10 specific problem. On Windows7 it works:

![http://tho-otto.de/screenshots/Screenshot_20190527_130555.png](http://tho-otto.de/screenshots/Screenshot_20190527_130555.png)

This was running Windows7 in VirtualBox, and H: is my home directory on linux.

Can you test that also on Windows7?

**Comment by mikrosk** [comment]
Unfortunately, I can't. @vinriviere?

However you can download Windows 10 Enterprise for free here: https://www.microsoft.com/en-us/evalcenter/evaluate-windows-10-enterprise (90-days trial) if you have some time for installation. :)

**Comment by mikrosk** [comment]
Btw, Windows builds need more love / testing in general - for instance, I can steadily reproduce a gcc internal error on aranym-jit for Windows while it works normally on aranym-jit/Linux or aranym-mmu/Windows (every other setting is the same). Quite scary.

**Comment by th-otto** [comment]
Ok, while looking after some other bug, i encountered something really strange:

on linux, in my home directory:
```
$ ls -l AA/bin/bash atari/aranym/tools/LibcWrapGenerator.pl
-rwxr-xr-x 1 sebilla users 1911109 27. Feb 15:09 AA/bin/bash
-rwxr-xr-x 1 sebilla users   10602  2. Jun 16:07 atari/aranym/tools/LibcWrapGenerator.pl
```

Same in cygwin, with linux home directory mounted as H:

![http://tho-otto.de/screenshots/Screenshot_20190602_190855.png](http://tho-otto.de/screenshots/Screenshot_20190602_190855.png)

The files in atari/aranym/tools correctly display the x-bit, the files in bin don't. Any idea what's going on there? There are no symlinks involved, both are real directories, and all directories leading to the path(s) have the same permission 755 on linux.

Update: that seems to be some strange cygwin magic:

```
$ ls -l atari/aranym/tools/testit*
-rw-r--r-- 1 sebilla users  0  2. Jun 19:20 atari/aranym/tools/testit
-rw-r--r-- 1 sebilla users 10  2. Jun 19:21 atari/aranym/tools/testit.sh
```

Note that both files are *not* executable. testit.sh however has a hash-bang line '#!/bin/sh'

In Aranym those files look like:

![http://tho-otto.de/screenshots/Screenshot_20190602_192446.png](http://tho-otto.de/screenshots/Screenshot_20190602_192446.png)

The testit.sh script there has the executable script set, although the actual file isn't.

I guess that has something to do with the fact that H: on cygwin is outside cygwins root directory and has a seperate entry in the mount table.

**Comment by th-otto** [comment]
Another note: the H: drive in my case is actually a network share in VirtualBox. Maybe thats add to the confusion.

**Comment by vinriviere** [comment]
Just tested with ARAnyM 1.1.0 on Windows: not better. It seems that in official builds of ARAnyM for Windows, the MiNT x flag is not recovered from Cygwin. I guess that all that stuff goes through the FreeMiNT's GEMDOS extended API, and the x flag is not properly forwarded.

**Comment by th-otto** [comment]
I cannot test with Windows10 currently, but see pictures above. I tested that also with Aranym1.0.2 which behaves the same, so atleast it is not a regression.

>and the x flag is not properly forwarded.

No, at least in my configuration, that is not the case. I get the same missing xflag already in the cygwin bash, without running aranym at all. I can also verify with debug printfs that the stat call does not return the xbit on e.g. bin/bash.  So this is a cygwin bug  and/or missing feature depending on where the file is actually mounted in windows.

So please check carefully where the directory that you use for the hostfs comes from, and whether a bash running just in cygwin actually returns the correct bits.

**Comment by mikrosk** [comment]
> The files in atari/aranym/tools correctly display the x-bit, the files in bin don't. Any idea what's going on there?

Actually, I have encountered a similar bug while testing this one. It really seemed like this bit is (un)set by random. For instance it, one `configure` would work, other wouldn't.

**Comment by vinriviere** [comment]
> So please check carefully where the directory that you use for the hostfs comes from, and whether a bash running just in cygwin actually returns the correct bits.

Of course I checked that with the `stat` command on both sides, otherwise I wouldn't have complained.
In my case, everything is good on the Cygwin side, and `x` is flag missing on the MiNT side.

BTW, with `stat` I see that the UID/GID values are different. Maybe that could also affect the `x` bit?
I remember that the MiNTLib translates POSIX calls to MiNT GEMDOS calls, then I guess that the `hostfs` driver does the opposite. Maybe some data is lost (x flag?) during the process?

**Comment by th-otto** [comment]
>Of course I checked that with the stat command on both sides, otherwise I wouldn't have complained.

Yes, of course, sorry ;)

Did some more tests, this time with a directory located directly on a ntfs filesystem. The directory is ~/minttest on cygwin, mounted as D: drive in mint.

```
$ ls -l ~/minttest/bin
total 2269
-rw-r--r-- 1 ich None  161984 Feb 28 10:58 basename
-rwxr-xr-x 1 ich None 1911109 Feb 27 15:09 bash
-rw-r--r-- 1 ich None  244024 Feb 28 10:58 date
-rwxr-xr-x 1 ich None     273 Jul 22  2007 netsetup.sh
```

(by purpose, i only had set the executable bit set on bash)

The same directory in a terminal in mint looks like:
```
$ ls -l D:/bin
total 1135
-rw-r--r-- 1 197609 197121  161984 Feb 28 09:58 basename
-rw-r--r-- 1 197609 197121 1911109 Feb 27 14:09 bash
-rw-r--r-- 1 197609 197121  244024 Feb 28 09:58 date
-rwxr-xr-x 1 197609 197121     273 Jul 22  2007 netsetup.sh
```

And this is what i get from a debug output in aranym from the last command:
```
stat64: C:/home/minttest/bin 40755 40755
stat64: H:/AA/etc/passwd 100644 100644
stat64: H:/AA/etc/group 100644 100644
stat64: C:/home/minttest/bin/basename 100644 100644
stat64: C:/home/minttest/bin/bash 100644 100644
stat64: C:/home/minttest/bin/date 100644 100644
stat64: C:/home/minttest/bin/netsetup.sh 100755 100755
```

The first number after the path there is the st_mode field as returned by the stat() call from cygwin, the 2nd the value passed back to mint. As you can see, it is already the stat() call from cygwin that kills the exec bit. The reason is probably because aranym translates the pathname to DOS style syntax (otherwise the user would have to use posix style pathnames like /cygdrive/x/somedir in the config file and that is hardly to explain), and because of [this](https://github.com/cygwin/cygwin/blob/d79aa0f5939be2640b90971d022b98054b86d249/winsup/cygwin/path.cc#L932-L937) of the cygwin library.

>BTW, with stat I see that the UID/GID values are different.

Yes, that is normal (the same happens on linux, too). It would be difficult to map the hosts uid/gid to a mint one, especially since it would have to work in both directions when you create files. Another problem is that linux usually uses 32-bit values, while mint uses only 16bit in some places (like Dxreaddir()).

**Comment by vinriviere** [comment]
> The reason is probably because aranym translates the pathname to DOS style syntax (otherwise the user would have to use posix style pathnames like /cygdrive/x/somedir in the config file and that is hardly to explain),

Ah, ARAnyM doesn't assume the fact that it is actually a Cygwin executable 😞
As such hacks are involved, I'm no more surprised that bad things happens.

> and because of [this](https://github.com/cygwin/cygwin/blob/d79aa0f5939be2640b90971d022b98054b86d249/winsup/cygwin/path.cc#L932-L937) of the cygwin library.

Good catch. This MOUNT_NOACL flag is definitely the culprit. In that case, Cygwin emulates the x flags using some heuristics. DOS-style paths should never be used in Cygwin, that's bad practice.

Demonstration:
```
touch a
chmod 755 a

stat a
...
Access: (0755/-rwxr-xr-x)

stat '.\a'
...
Access: (0644/-rw-r--r--)
```

Personally, I would be happy with Cygwin paths in the ARAnyM config file. I even recompile Hatari for plain Cygwin to have the benefit of such feature.

If you really want to hide Cygwin paths, do what you want for display. If the user has manually put DOS-style paths in the configuration file, that's his responsibility. But if the user (like me) has explicitly put Cygwin paths (or relative paths) in the configuration file, please don't mess them.

**Comment by th-otto** [comment]
>As such hacks are involved, I'm no more surprised that bad things happens.

I really thought something of it.

>Personally, I would be happy with Cygwin paths in the ARAnyM config file

I would not mind either. But it would be hard to explain to casual users where the paths they enter are actually located when they open an Explorer window.

BTW that hostfs part is actually the main reason why it is stlll a cygwin binary. If there would be an easy way to emulate things like posix file permission, symlinks etc., i would prefer to compile it as plain windows executable instead.

I've added a fix now that should solve the issue. It still does not work with my first example, but i think this is a problem of the network share not reporting those flags.

**Comment by joysfera** [comment]
@th-otto regarding emulating POSIX stuff, wondering if Linux Subsystem for Windows 10 May 19 edition couldn't help here.

Maybe we'll be able to run even pure Linux binaries in Windows soon and then userland additional emulating layers (Cygwin) will not be needed anymore.

**Comment by th-otto** [comment]
But that linux subsystem is only avaiiable for Windows10+, so that would mean we have to provide different binaries for windows.

**Comment by joysfera** [comment]
Not really. Windows 7's support will end in just seven months so it's basically almost dead now. Windows 8.1 is probably not used much so the Windows 10 will be pretty much the only version of Windows in general use soon.

**Comment by mikrosk** [comment]
> wondering if Linux Subsystem for Windows 10 May 19 edition couldn't help here.

Not really. Even if you forget graphics (this is actually possible but without 3D acceleration) and sound, there are other still several limitations, for instance `tun` is not available and wont be for a long time.

Personally I compile everything in WSL but in the end, I have to run aranym.exe from WSL's command line.

**Comment by vinriviere** [comment]
I remember that long ago, there was a special test binary of MinGW ARAnyM, and that it worked very well for standard usage.
On the other hand, I have always been very disappointed about approximations performed by Cygwin POSIX to MiNTLib POSIX conversion. Namely: stat differences, x flag, UID, GID, symlink issues, lack of lock API... One of the first usages I tried was to configure/make some software from FreeMiNT+hostfs. It often fails at some point, due to issues in the features I have just listed. Even `passwd` fails because of missing lock API. OpenSSH fails to run bash because it lacks the x flag. etc. etc. So in conclusion, don't trust hostfs for serious POSIX stuff. Use ext2 partitions instead.

That being said:

1) I would be happy enough with a MinGW ARAnyM and no support at all for POSIX, not even the x flag. This basically the setup we have now, with that broken x flag. And it is good enough for basic stuff. In other words, such configuration would be good for mounting a simple directory containing a few TOS/MiNT programs or data, when POSIX specific features are not required. Then use ext2 partitions if you need accurate POSIX compatibility.

2) A luxurious solution would be this one. Use MinGW build by default. But if a POSIX path is detected in ARAnyM configuration file, then dynamically use Cygwin functions (instead of Win32) to implement hostfs functions. This way, we have the best of both world: plain Win32 support by default, then Cygwin filesystem support if the user requests it at runtime. I'm not sure that it is possible to dynamically use Cygwin that way, though.
This is probably an overkill solution. Concretely, solution 1) would be enough for most needs. If x flag is officially unsupported, then people couldn't complain that it doesn't work.

On the other hand, you could provide 2 ARAnyM binaries for Windows:
- One using pure MinGW for most users, with no POSIX / flag x emulation
- One using Cygwin for Cygwin enthusiasts, with unhacked /cygdrive paths in the config file.
As I told you, I already use such pair of binaries for Hatari, and that's fine for me.

**Comment by th-otto** [comment]
>I remember that long ago, there was a special test binary of MinGW ARAnyM, and that it worked very >well for standard usage.

I haven't tried for some time, but it should still be possible to compile aranym for mingw.

>approximations performed by Cygwin POSIX to MiNTLib POSIX conversion.

What "approximations"? There are only needed conversions where the flag values differ.

>UID, GID

As already explained, that is hardly manageable in an easy way. Did you ever mount a ntfs drive on linux, using the ntfs3g driver? It suffers from a similar problem. And you also have that problem when mounting a nfs or samba share. Unless the uids/gids on the 2 systems are identical, you will run into trouble mapping them from one system to the other.

>lack of lock API...

That has already been addressed in the mint part of the hostfs driver. Aranym itself can't do that because it doesn't know anything about mint processes.

>then dynamically use Cygwin functions (instead of Win32) to implement hostfs functions.

That's technically not possible. cygwin uses newlib, which is different from msvcrt. When you dynamically load it later, there will be already certain files open, and you cannot pass their FILE pointers and/or handles to the cygwin library. Also the handler that catches segmentation faults (which is mainly needed for the JIT version) needs to hook itself up in the exception chain installed by cygwin,  and that can only be done at startup.

>On the other hand, you could provide 2 ARAnyM binaries for Windows:.

That should be manageable. It's mostly a matter of just another entry in the travis.yml. But remember the original problem reported by Miro, which IIRC was caused by some executables not being run because of the missing x-flag.

**Comment by mikrosk** [comment]
Confirmed, commit 6f5d502 allows `sshd` to run on Windows 10 flawlessly.

**Comment by joysfera** [comment]
@th-otto thanks for the fix, looking forward to releasing new ARAnyM version ASAP.

Regarding the UID/GID mapping - it's obvious that full 1:1 mapping is impossible without sharing the user databases and even that would not work well. Would it help @vinriviere if we had a ARAnyM config option for specifying UID and GID that would make all files from the host appear on the mint side with these values? I haven't really thought about it properly, it might cause more troubles (especially when say the default values would be 0/0 => root:root), so just kinda brainstorming here. @th-otto any idea?

**Comment by th-otto** [comment]
Fully mapping is almost impossible i think. ntfs3g on linux has some support for this by putting a file in /.NTFS-3G/UserMapping of the mounted drive, but it is difficult to setup. Samba or nfs don't even have an option for that, and i guess they have a reason for not doing so. Using some option to override the uid/gid might be a solution i think, most filesystem drivers on linux already support such an option. If it does not work well, then you just should not use it.

Of course there will be still some inconsistencies. If your are running as root on mint (which is probably the case most of the time unless you are using some init that changes your uid before launching AES), that does not suddenly give you root access to the host, and you still won't be able to change the uid/gid of files on the host from mint.

**Comment by joysfera** [comment]
That proposed mapping would at least help to make files created by the MiNT user (supposedly running under an user ID different from 0) look like they belong to it.

Wondering if that is indeed what @vinriviere or @mikrosk needed.

**Comment by joysfera** [comment]
I don't understand why you mention NFS - I thought we were trying to make FreeMiNT running better on host filesystem, no networking involved. Anyway, we can leave such option for later and just release the current fix to see if Vincent is happier.

**Comment by th-otto** [comment]
i only mentioned it to see how it is handled there, since they essentially have the same problem.

**Comment by vinriviere** [comment]
Thanks @th-otto for the fix! I haven't tried myself, but as @mikrosk  confirmed it works for him, I believe everything is OK.

When I talked about approximations, basically it was: run the `stat` command on the same file from host and MiNT sides. Theoretically, we should see the same thing. But most of the time, this has no importance.

About hostfs features, I see 3 levels of usage:

1) Basic usage. Mount a directory to run plain TOS/MiNT programs. Extended flags such as x and UID/GID, and even symlinks have no importance. This is an extremely useful feature, similar to Hatari and Steem GEMDOS drive emulation.

2) Extended usage to run POSIX software. This includes proper handling of the x flag, as required by sshd. This also requires the presence of lock API (even faked, no importance) so utilities such as `passwd` can do their job. We can agree that `passwd` and `sshd` are really basic POSIX commands, and anyone would expect them to work.

3) Advanced usage: be able to compile POSIX software from hostfs. This may be complicated because configure scripts sometimes do tricky things which may require accurate behaviour with UID/GID, symlinks, etc. I remember that this was one of the first things tried to do, and I was very disappointed because I encountered several unexplainable configure bugs because of hostfs issues. Specially because I didn't understand that my problems came from hostfs. I can't tell precisely what went wrong.

Adding a parameter for UID/GID mapping may be a good idea. On the other hand, I don't know a scenario where this would be really required. Concretely, you should consider the 3 levels of usage I have just listed, and decide what needs to be done and what will not be implemented, by design.

PS: I haven't tested recent MiNT builds regarding to previous lock issues.

**Comment by th-otto** [comment]
> 1.Basic usage.

Yes, i'm quite confident that there should be no major issues with that.

> 2. Extended usage to run POSIX software.

Yes, this should also work (and did so at least on unix based hosts). I'm sorry that i haven't noticed until the fix that it did not work as expected on cygwin so far. The reason is simply that i don't use cygwin that much (not because i don't like it, but it is a posix environment after all, which i already have directly on the host).

> 3. Advanced usage: be able to compile POSIX software from hostfs. 

That should work, too. Again, i haven't tried it on cygwin, but i have already compiled gcc successfully on Aranym running on linux (just took about ~20 hours even with JIT).

>I haven't tested recent MiNT builds regarding to previous lock issues.

Yes, i haven't noticed that locking did not work for years, until i tried to compile&run rpm, which uses file locking to prevent multiple runs on the same database. It has been implemented by https://github.com/freemint/freemint/commit/7e31c3618f446e806a39ef6fe83bda1573e38453

>I don't know a scenario where this would be really required.

At least that would be nicer than to display some meaningless UIDs in mint because they can't be resolved. For me, i have just solved that by adding an entry to /etc/passwd with the same UID as on linux, so files i create from mint will be displayed with my user name. But that simple "trick" only works for files owned by me.

**Comment by mikrosk** [comment]
> > 1. Advanced usage: be able to compile POSIX software from hostfs.
> 
> That should work, too. Again, i haven't tried it on cygwin, but i have already compiled gcc successfully on Aranym running on linux (just took about ~20 hours even with JIT).

Maybe gcc is fine but I have encountered this kind of random bugs as well (in cygwin it is much worse but native linux environment isn't perfect either). After some time I simply gave up and moved to an ext2 partition. Most of the time something fails in `./configure` but if `Makefile` relies on some unusual magic with symlinks (or even hard links!), UIDs, ... all goes downhill.

> > I don't know a scenario where this would be really required.
> 
> At least that would be nicer than to display some meaningless UIDs in mint because they can't be resolved.

Certainly there is one -- to run `sshd` without any tricks. If ~/.ssh has owner 1000/1000, it complains even if running as root. So I have to disable the strict mode checking to make it work.

**Comment by th-otto** [comment]
>if ~/.ssh has owner 1000/1000, it complains even if running as root

There is a simple solution to that: just do a "chown 0:0 sshd" on the host ;)

**Comment by mikrosk** [comment]
> There is a simple solution to that: just do a "chown 0:0 sshd" on the host ;)

if you mean chown -R 0:0 .ssh on the host then this is not exactly comfortable to have a root-protected folder in my $HOME. :) If you mean "chown 1000:1000 sshd" in FreeMiNT, I think that wouldn't work, UID  is assigned by (and compared against) the OS, it isn't read from the (freemint) sshd binary, is it?

**Comment by th-otto** [comment]
Ah ok the ~/.ssh folder is the problem, when not owned by the uid used by mint? Yes, having such a directory owned by root would not be very nice.

>it isn't read from the (freemint) sshd binary, is it?

No, it currently is read from the hostfs (if sshd is located there), and forwarded unchanged to mint. You could try to change it to suid 1000/1000, but maybe then mint complains about missing permissions, depending on what it needs to do.

**Comment by paulwratt** [comment]
is there any reason why a hostfs cant 'ln -s /etc/passwd' - it appears part of the problem here is the default use of 0:0, where most OS's will start Aranym from 1000:1000

If I remember rightly, there were some other benefits to running the MinGW version, with the (only?) major drawback being lack of POSIX drive access, so I believe 2 versions for Windows would be fine

but I think @th-otto you need a vm with a clean cygwin for testing - unless there is a way to test it with travis builds (not simply I think).

**Comment by paulwratt** [comment]
lack of networking too with MinGW maybe, but native graphics. both versions would be able to be tested on the VM. is it worth distributing a image for dev purposes? developing automated tests?

**Comment by th-otto** [comment]
>is there any reason why a hostfs cant 'ln -s /etc/passwd'

It can:
```
$ ln -s /etc/passwd
$ ls -l passwd
lrwxrwxrwx 1 sebilla users 11 Jun 11 19:22 passwd -> /etc/passwd
```

>there were some other benefits to running the MinGW version

Looks like the mingw-JIT version currently crashes. I'm not sure however whether that ever worked.

>I think @th-otto you need a vm with a clean cygwin for testing 

Why do you think it is not clean?

>lack of networking too with MinGW maybe

Did not try yet, but i think that should work. The cygwin version uses Windows-Calls in the network code, not cygwin-specific devices.


PS.: this issue is closed, and the things you  are talking about are not related to it. If you have any new issues/suggestions, please discuss that on the aranym ML.
