### ISSUE TITLE
Middle mouse button to release input grab

### ISSUE THREAD

**Issue by vinriviere** [aranym/aranym#27]
How is this feature supposed to work? It is advertised in the title bar, but nothing happens when I press the middle mouse button.
I use Windows 10 64-bit.

BTW: I remember having requested this feature long ago, because it was very convenient with WinUAE.

**Comment by joysfera** [comment]
When you press the middle mouse button the input devices (keyboard and moouse) are released so you can say move the mouse pointer out of ARAnyM window.

**Comment by vinriviere** [comment]
I can just say that it does nothing on Windows. Whatever version.

**Comment by mikrosk** [comment]
> I can just say that it does nothing on Windows. Whatever version.

Can't confirm this. It works as expected here on Win10, pretty recent aranym build. Perhaps a configuration issue?

**Comment by vinriviere** [comment]
Tested on a different machine with Windows 10: it works well. There is something wrong with my main machine. I will report progress here.

**Comment by vinriviere** [comment]
Ah, I forgot that I already discussed that with Petr in 2012. Fact is that middle button can only release input grab **if** `WheelEiffel = No` in the config file. And it was set to `Yes` in my config.
IMHO, ARAnyM should be able to enable both Eiffel mouse wheel and "middle button release". But in that case, it would be impossible to simulate Eiffel middle button. So there should be an option to enable/disable "middle button release". And in any case, advertise in the title bar only what is supposed to work using the current settings, otherwise that's misleading.

In my initial feature request, I just wanted to be able to use the middle button as hotkey, so I could manually map it to Ungrab. This would be a nice default. Current special feature for middle button is actually a bit weird. It would make more sense to use it as generic hotkey.

**Comment by th-otto** [comment]
>So there should be an option to enable/disable "middle button release". 

That's doable, but would be dangerous. You could end up with not being able to release the grab at all, rendering the system unusable if some atari app hangs in aranym.

>And in any case, advertise in the title bar only what is supposed to work using the current settings, >otherwise that's misleading.

That's true.

**Comment by vinriviere** [comment]
> That's doable, but would be dangerous. You could end up with not being able to release the grab at all, rendering the system unusable if some atari app hangs in aranym.

Would it be worse than the current situation, with WheelEiffel = Yes, where middle button doesn't do anything?

Personally, I almost always exit ARAnyM with Pause then Shutdown.

**Comment by th-otto** [comment]
>Would it be worse than the current situation, with WheelEiffel = Yes

Hm, maybe not. And there is also a keyboard shortcut. So maybe this could be implemented.

>It would make more sense to use it as generic hotkey.

But then it should be restricted to certain options. There are hotkeys for reboot & shutdown, i don't think it would be a good idea to allow that mapping. When you are used to the current behaviour and press middle mouse button just to see aranym shutting down, that would be a bad surprise.

>Personally, I almost always exit ARAnyM with Pause then Shutdown.

I personally just close the window. But that only works because i don't have ext2 partitions, otherwise it would be safer to shutdown Aranym from inside mint.

**Comment by vinriviere** [comment]
> I personally just close the window.
I would love to do that, but I can't because middle button doesn't ungrab, do you remember the initial issue?

**Comment by th-otto** [comment]
Yes, that's why i use GrabMouse=No so i don't have to press middle button to release it ;)

But i just came up with another question: if you want to use eiffel option, so mouse wheel events are sent to the emulated system, but use middle button for something else, what does the emulated system do with the wheel events? Aren't they just translated to arrow key presses, eg. the same result as if you did not use the eiffel setting at all?

To the possible hotkeys, these are currently
- Enter Setup
- Quit Aranym
- Reboot
- ColdReboot
- Ungrab
- Enter Debugger (only available if you manually enabled that when configured aranym)
- Take screenshot
- Toggle Fullscreen
- Toggle Sound

IMHO there aren't that many options that make sense for middle button, these could be Setup/Ungrab/Screenshot/Fullscreen

**Comment by vinriviere** [comment]
> if you want to use eiffel option, so mouse wheel events are sent to the emulated system, but use middle button for something else, what does the emulated system do with the wheel events?

Middle button should ungrab, then mouse wheel should generate Eiffel wheel events. Simple. So the emulated system can do whatever it wants with the wheel. But it doesn't make sense if that ungrab can't be disabled, otherwise the user will never be able to use the Eiffel middle button, if he wants.

I can live with WheelEiffel = No, it this is the official solution. But please remove that ungrab advertisement in the title when WheelEiffel = Yes, as this is just a lie.

**Comment by joysfera** [comment]
@vinriviere I don't think you're correct when you say that middle button should ungrab even when Eiffel wheel emulation is enabled because then the user would never get the middle mouse button press/release event. I believe that was the point - the Eiffel emulation brings third mouse button+wheel and if you want to use it (Eiffel=Yes) then the ungrab must not happen on middle button, otherwise you'll get unhappy. I understand that you might be using just the wheel and not the middle button but I suppose others might be using also the third button. Hard to say without making a poll :)

**Comment by th-otto** [comment]
That problem will be solved when it is configurable. Then you can say what to do with middle button, whether that should also be send to eiffel or not. And if not, whether it should ungrab or do something else.

**Comment by mikrosk** [comment]
Funnily enough, I bit myself as well. ;) https://github.com/aranym/aranym/issues/15

So that makes at least two of us, I would say Aranym power users, who were caught in this trap. The least I can imagine is print something to the console, like "middle button ignored due to `WheelEiffel = Yes`"

**Comment by joysfera** [comment]
@mikrosk such a message would be nonsense. The middle button is not ignored. https://didierm.pagesperso-orange.fr/eiffel-e.htm

**Comment by vinriviere** [comment]
@mikrosk Sorry, I missed your issue.

By thinking twice: I don't remember well why I had WheelEiffel = Yes in my configs. Maybe I just tried it in early days, when I wasn't fully understanding the consequences. Or maybe this was to debug EmuTOS regarding of Eiffel scancodes. Anyway, now I see that I don't really need WheelEiffel = Yes anymore for daily usage. Furthermore, yesterday I tried snapshot 57c5213 and I saw that Thorsten had fixed the misleading title, thanks for that.
So there is no more mystery or misleading message. As far as I'm concerned, the current situation is good enough. So you can close this issue.

**Comment by th-otto** [comment]
I think that it might still be a useful feature, so that is now implemented, too.

**Comment by vinriviere** [comment]
I have just tested the latest ARAnyM snapshot. Very good, Thorsten 👍 You have added all the options one could dream of.

2 remarks:
- Again, the title bar should reflect the real function of the middle button. And not something wrong. If you prefer, it could just display the ungrab message (as it is critical), but only when it is supposed to work.
- It is cool to be able to open the menu with the middle button. In that case, it could also be cool to be able to close it.

**Comment by th-otto** [comment]
The title bar should already be correct regarding whether middle mouse releases grab or not. Adding text to what else the middle button does would make it too long, i think. Only thing that could be added maybe is when it opens the setup, since text for that is already there.

Closing the setup will be doable, but only while the main dialog is active (like it is already the case fpr the Pause key)
