### ISSUE TITLE
Tap isn't detected in windows 10

### ISSUE THREAD

**Issue by dyharlan** [aranym/aranym#6]
I have a problem when tryimg to get networking to work. For some reason aranym doesnt detect the tap driver installed on my system even after it's renamed tap0 for compatiblity. So I couldnt get networking to work no matter what I do. I'm using the latest tap driver from openvpn from their site.

My setup consists of: windows 10 10240, FreeMiNT converted to SpareMiNT, MyAES 0.97, FVDI, THING 1.27e and aranym-jit 1.0.2

I tried asking in atari-forum.com and the newsgroup but to no avail. Please help

**Comment by mikrosk** [comment]
I'm in a similar situation but my results are even worse - I installed the latest OpenVPN, set its IP to the one I use in Linux, renamed it to tap0 as you did but when I start latest Aranym, all I get is an infinite stream of:
`ETHERNETDriver::readPacket() - length -1 > 9000`
What I don't understand is that what role plays that coLinux win32-tap driver mentioned in the wiki. Is it the same thing which gets installed by OpenVPN? Does need to be installed side-by-side with OpenVPN?

Anyway, if the coLinux driver has to be installed, we are screwed because it doesn't support x64 Windows. There is a branch with 64-bit code on SF.net but no release (and it seems to be pretty abandoned).

**Comment by mikrosk** [comment]
Ha, I got it working! All I had to do is to set Media Status to "Always connected" as per http://www.atari-forum.com/viewtopic.php?p=227166#p227166.

So there is nothing wrong with Aranym and/or Windows compatibility, OpenVPN is all that is needed.

What is even crazier, I could ssh from my WSL'ed Ubuntu in Windows 10 to the Aranym instance:

![image](https://user-images.githubusercontent.com/3062260/57770835-75710000-7711-11e9-99e0-6d571e890d5f.png)

**Comment by vinriviere** [comment]
Something must be missing in ARAnyM. I already noticed that ARAnyM needed to check that "Always connected" option in the Windows TAP driver, while other software (coLinux? I don't remember) don't require that. ARAnyM should be able to "connect the cable" when the Atari network interface is enabled.

**Comment by th-otto** [comment]
That might be possible, but to set this status is highly system dependent. I'm also not sure whether that will even work on windows, because aranym is actually using cygwin there. And since there is no button in either mint or aranym where the user could change the state, i think just setting the flag in openvpn is the easiest solution.
